@startuml

entity users {
  *user_id : serial (PK)
  --
  firstname
  lastname
  phone_number
  email : unique, not null
  password
  role_id : FK
}

entity roles {
  *role_id : serial (PK)
  --
  role : unique, not null
}

entity orders {
  *order_id : serial (PK)
  --
  user_id : FK, not null
  carport_id : FK
  building_material_id : FK
  staff_id : FK
  total_price : numeric
}

entity order_status_history {
  *order_id : FK
  *update_date : timestamp
  --
  status : text
}

entity order_items {
  *order_id : FK
  --
  carport_id : FK
  building_material_id : FK
  quantity : int, not null
}

entity carports {
  *carport_id : serial (PK)
  --
  width : numeric, not null
  length : numeric, not null
  height : numeric, not null
  roof_type : text, not null
  roof_angle : numeric, not null
  post_building_material_id : FK
  beam_building_material_id : FK
  rafter_building_material_id : FK
  fascia_building_material_id : FK
  total_price : numeric
}

entity building_materials {
  *building_material_id : serial (PK)
  --
  name
  description
  width
  material_type : text, not null
  buckling_load : numeric
  post_gap
  support_gutters : boolean
  is_active : boolean, not null
}

entity predefined_lengths {
  *predefined_length_id : serial (PK)
  --
  length : int, not null
}

entity price_history {
  *price_history_id : serial (PK)
  --
  carport_id : FK
  building_material_id : FK
  predefined_length_id : FK
  cost_price : numeric
  sales_price : numeric
  valid_from : date
  valid_to : date
}

' Relationships
users ||--o{ orders
users ||--o{ order_status_history : handles
users ||--o{ order_items
users ||--o{ roles : has
orders ||--o{ order_status_history
orders ||--o{ order_items
orders ||--|| users : placed_by
orders ||--|| users : handled_by
orders ||--o| carports
orders ||--o| building_materials
order_items ||--o| carports
order_items ||--o| building_materials
carports ||--o| building_materials : uses
price_history ||--o| building_materials
price_history ||--o| carports
price_history ||--o| predefined_lengths

@enduml
